[changelog]
header = """
# Changelog\n
"""
body = """
{%- macro remote_url() -%}
  https://github.com/postfinance/topf
{%- endmacro -%}

{% if version -%}
  ## [{{ version | trim_start_matches(pat="v") }}] - {{ timestamp | date(format="%Y-%m-%d") }}
{% else -%}
  ## [Unreleased]
{% endif -%}

{% for group, commits in commits | group_by(attribute="group") %}
### {{ group | striptags | trim | upper_first }}
{% for commit in commits %}
  - {% if commit.breaking %}**BREAKING**: {% endif %}{% if commit.scope %}**{{ commit.scope }}**: {% endif %}\
      {{ commit.message | upper_first }} ([{{ commit.id | truncate(length=7, end="") }}]({{ self::remote_url() }}/commit/{{ commit.id }}))
{%- endfor %}
{% endfor %}
"""
trim = true

[git]
conventional_commits = true
filter_unconventional = false
protect_breaking_commits = true
commit_parsers = [
  { message = "^feat", group = "<!-- 0 -->Features" },
  { message = "^fix", group = "<!-- 1 -->Bug Fixes" },
  { message = "^doc", group = "<!-- 2 -->Documentation" },
  { message = "^perf", group = "<!-- 3 -->Performance" },
  { message = "^refactor", group = "<!-- 4 -->Refactor" },
  { message = "^style", group = "<!-- 5 -->Styling" },
  { message = "^test", group = "<!-- 6 -->Testing" },
  { message = "^chore\\(release\\)", skip = true },
  { message = "^chore\\(deps\\)", skip = true },
  { message = "^chore|^ci", group = "<!-- 7 -->Miscellaneous" },
  { message = "^build", group = "<!-- 8 -->Build" },
  { message = "^revert", group = "<!-- 9 -->Revert" },
  { message = "^Merge pull request", skip = true },
  { message = "^Merge branch", skip = true },
  { message = "^initial commit$", skip = true }
]
filter_commits = false
tag_pattern = "v[0-9].*"
sort_commits = "oldest"
